nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: "app-template-nestjs"
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

app:
  containerPort: 3000
  healthPath: /health
  extraEnv: []
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 2
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 10
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

mongodb:
  enabled: true
  image:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent
  service:
    port: 27017
  auth:
    enabled: false
    username: appuser
    password: apppass
    database: appdb
    existingSecret: ""
  persistence:
    enabled: true
    accessModes: [ "ReadWriteOnce" ]
    size: 2Gi
    storageClass: ""
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
