{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-template-nestjs.mongodb.fullname" . }}-auth
stringData:
  username: {{ .Values.mongodb.auth.username | quote }}
  password: {{ .Values.mongodb.auth.password | quote }}
  database: {{ .Values.mongodb.auth.database | quote }}
{{- end }}
