{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app-template-nestjs.mongodb.fullname" . }}
  labels:
    {{- include "app-template-nestjs.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "app-template-nestjs.mongodb.fullname" . }}-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongo
              containerPort: {{ .Values.mongodb.service.port }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.auth.database | quote }}
          {{- if .Values.mongodb.auth.enabled }}
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-auth" (include "app-template-nestjs.mongodb.fullname" .)) .Values.mongodb.auth.existingSecret }}
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-auth" (include "app-template-nestjs.mongodb.fullname" .)) .Values.mongodb.auth.existingSecret }}
                  key: password
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
  volumeClaimTemplates:
    {{- if .Values.mongodb.persistence.enabled }}
    - metadata:
        name: data
      spec:
        accessModes: {{- toYaml .Values.mongodb.persistence.accessModes | nindent 10 }}
        {{- if .Values.mongodb.persistence.storageClass }}
        storageClassName: {{ .Values.mongodb.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
    {{- else }}
    []
    {{- end }}
{{- end }}
